version: '2'
services:
  blueplanet:
    build: .
    container_name: blueplanet
    volumes:
      - .:/home/project
    networks:
      static-network:
        ipv4_address: 172.51.0.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.51.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 192.168.0.1/24
